"""連接能力目錄。ready=本版有實作；guide=僅提供官方連接指引。"""
CATALOG = [
    dict(id="files", name="自己的檔案", group="生意資料", mode="local", stage="ready", nodes=["迎客","成交","養客"], benefit="把名單與交易紀錄放進同一個工作台。", fallback="可直接輸入一筆，或匯入 CSV。", cost="不需 API", url="", steps=["在脈絡頁選擇 CSV，先看欄位與前幾筆。","確認要帶入的資料，再開始匯入。"]),
    dict(id="openstreetmap", name="街道地圖", group="找客", mode="keyless", stage="ready", nodes=["找客"], benefit="把已有位置的對象放到地圖，搭配名單一起看。", fallback="圖資未載入時，名單與已存位置仍保留。", cost="不需金鑰；圖資需要網路", url="https://www.openstreetmap.org/copyright", steps=["有經緯度的對象會直接出現在地圖。","也能從 CSV 帶入 latitude、longitude。"]),
    dict(id="google_places", name="Google 商家搜尋", group="找客", mode="key", stage="ready", nodes=["找客"], benefit="輸入地區與商家類型，找出可研究的合作對象。", fallback="先用自己的名單，或匯入商家搜尋工具產出的 CSV。", cost="Google 依 API 使用計費；搜尋前由你按鍵執行", url="https://console.cloud.google.com/apis/library/places.googleapis.com", steps=["在 Google Cloud 選擇自己的專案，確認帳務與預算通知。","開啟 Places API (New)，到「API 和服務 → 憑證」建立金鑰。","限制金鑰僅可使用 Places API，回到這裡貼上。","儲存後到地圖執行一次搜尋；成功回傳資料才會標示已驗證。"], secret_label="Places API 金鑰"),
    dict(id="notion", name="Notion", group="生意資料", mode="key", stage="ready", nodes=["迎客","養客","回客"], benefit="帶入自己已整理的 Notion 頁面，作為經營判斷的材料。", fallback="先存在自己的電腦，隨時再接。", cost="依自己的 Notion 方案", url="https://www.notion.so/profile/integrations", oauth_url="https://developers.notion.com/guides/mcp/get-started-with-mcp", steps=["建議先從原助手的連接器選 Notion，由本人登入授權。","若要由本工作台直接讀取，建立自己的 internal integration。","將要讀取的頁面加入該 integration 的連線，再把 secret 貼在下方。","本版可驗證帳號、列出授權頁面並匯入文字；建庫與同步仍由原助手帶領。"], secret_label="Notion integration secret"),
    dict(id="google_business", name="自己的 Google 商家", group="口碑", mode="oauth", stage="guide", nodes=["找客","口碑"], benefit="整理自己管理的商家資料與評論。", fallback="先提供商家網址、評論截圖或匯出內容。", cost="需商家管理權限與 API 存取資格", url="https://developers.google.com/my-business/content/prereqs", steps=["先確認自己是該商家的擁有者或管理員。","依官方指引確認 API 存取資格與 OAuth 設定。","這項需要獨立整合；Google 商家搜尋的金鑰不會取得商家管理權。"]),
    dict(id="google_sheets", name="Google 試算表", group="生意資料", mode="oauth", stage="guide", nodes=["迎客","成交","回客"], benefit="沿用原本的名單與交易表。", fallback="先從試算表下載 CSV，即可匯入。", cost="沿用自己的 Google 帳號", url="https://developers.google.com/workspace/sheets/api/quickstart", steps=["從檔案 → 下載 → CSV 取得要使用的分頁。","若要持續讀取，再由助手設定 Google OAuth 並選定表格。"]),
    dict(id="instagram", name="Instagram／Facebook", group="社群", mode="oauth", stage="guide", nodes=["找客","迎客","口碑"], benefit="把自己的內容成效、詢問與客群線索放回獲客流程。", fallback="先提供自己的貼文網址、成效匯出或截圖。", cost="依帳號類型、權限與 API 範圍", url="https://developers.facebook.com/docs/instagram-platform/", steps=["先選這次需要的資料：內容、成效或詢問。","確認專業帳號與需要的權限，使用官方登入授權。","本版提供指引與材料匯入；不會自動發文或私訊。"]),
    dict(id="line", name="LINE 官方帳號", group="社群", mode="token", stage="guide", nodes=["迎客","養客","回客"], benefit="整理顧客詢問與跟進流程。", fallback="先放去除不必要個資的詢問摘要。", cost="依官方帳號方案與發送量", url="https://developers.line.biz/en/docs/messaging-api/getting-started/", steps=["確認使用的是 LINE 官方帳號。","由助手確認需要讀取、接收事件或發送的哪一種能力。","需要對外服務與驗證的事件接收，另行安排；目前不會發送訊息。"]),
    dict(id="analytics", name="網站與廣告成效", group="成效", mode="oauth", stage="guide", nodes=["找客","成交"], benefit="比較來源到詢問、訂單的實際關係。", fallback="先匯入同一期間的報表，確認單位與定義。", cost="依 GA4／廣告平台方案", url="https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries", steps=["選定自己的資源與報表期間。","先確認詢問／成交事件有正確紀錄。","再由助手設定最小範圍的讀取授權。"]),
    dict(id="commerce", name="電商與預約系統", group="生意資料", mode="adapter", stage="guide", nodes=["成交","養客","回客"], benefit="沿用既有訂單、預約與回購資料。", fallback="下載交易 CSV，先確認日期與金額欄位。", cost="依現有平台", url="https://shopify.dev/docs/api", steps=["先說明目前使用的平台與想看的資料。","提供匯出檔，或由助手查核該平台的官方 API。","預約與訂單狀態以原平台為準。"]),
    dict(id="agent_reach", name="公開網路研究", group="研究工具", mode="agent", stage="guide", nodes=["找客","口碑"], benefit="按需求讓原助手閱讀網頁、影片與公開討論。", fallback="原助手已有搜尋或瀏覽能力時優先使用。", cost="依實際使用的上游服務", url="https://github.com/Panniantong/Agent-Reach", steps=["先選本次需要閱讀的平台。","請助手檢查 Agent-Reach 與該平台的可用路徑。","只安裝需要的能力，登入授權由本人在官方介面完成。"]),
    dict(id="maps_scraper", name="本機商家名單工具", group="研究工具", mode="agent", stage="guide", nodes=["找客"], benefit="將已有的商家擷取流程接入名單與地圖。", fallback="本版可直接匯入工具產出的 CSV，不需先裝 Docker。", cost="需要 Docker 與本機資源；依工具實況", url="https://github.com/Mahanaicoach/google-maps-scraper-kit", steps=["讓助手先檢查 Docker 與工具是否已存在。","先小量執行，遵守資料來源的使用限制。","需要地圖座標時使用完整匯出；回到脈絡匯入 CSV。"]),
    dict(id="mcp", name="既有助手連接器 / MCP", group="研究工具", mode="agent", stage="guide", nodes=["找客","迎客","成交","口碑","養客","回客"], benefit="延用你原本助手已經連好的工具。", fallback="沒有連接器也能完成基礎流程。", cost="依連接的服務", url="https://modelcontextprotocol.io/docs/learn/architecture", steps=["在原助手的連接器設定中確認需要的服務。","由本人完成官方登入，助手測試可讀範圍。","助手把結果與來源寫回這個工作台；連接器設定不放進對話。"]),
]
BY_ID = {p["id"]:p for p in CATALOG}
